In [30]:
# Dependencies and Setup
import pandas as pd
import requests
import gmaps
import numpy as np
import sys
sys.path.append("..")
# Import API key
from config import g_key

import os
# Configure gmaps
gmaps.configure(api_key=g_key)

In [15]:
# 1. Import the WeatherPy_database.csv file. 
city_data_df = pd.read_csv("Weather_Database/WeatherPy_Database.csv")
city_data_df.head()

,City_ID,City,Country,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed,Current Description
0,0,New Ulm,US,44.3125,-94.4605,21.54,78,90,12.66,light snow
1,1,Atuona,PF,-9.8000,-139.0333,78.22,73,20,11.43,few clouds
2,2,Yellowknife,CA,62.4560,-114.3525,-12.59,94,90,5.75,light shower snow
3,3,Carnarvon,AU,-24.8667,113.6333,68.07,73,0,13.80,clear sky
4,4,Nemuro,JP,43.3236,145.5750,23.32,59,7,14.74,clear sky

In [31]:
# 2. Prompt the user to enter minimum and maximum temperature criteria 
min_temp = float(input("What is your desired minimum temperature for your trip? "))
max_temp = float(input("What is your desired maximum temperature for your trip? "))

What is your desired minimum temperature for your trip? 64
What is your desired maximum temperature for your trip? 92

In [32]:
# 3. Filter the city_data_df DataFrame using the input statements to create a new DataFrame using the loc method.
preferred_cities_df = city_data_df.loc[(city_data_df["Max Temp"] >= min_temp) &
                                       (city_data_df["Max Temp"] <= max_temp)]
preferred_cities_df

,City_ID,City,Country,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed,Current Description
1,1,Atuona,PF,-9.8000,-139.0333,78.22,73,20,11.43,few clouds
3,3,Carnarvon,AU,-24.8667,113.6333,68.07,73,0,13.80,clear sky
6,6,Arraial Do Cabo,BR,-22.9661,-42.0278,75.16,78,75,8.05,broken clouds
7,7,Kavieng,PG,-2.5744,150.7967,81.37,78,99,7.38,light rain
8,8,Aketi,CD,2.7388,23.7833,73.80,73,80,2.35,broken clouds
10,10,Oranjestad,AW,12.5240,-70.0270,82.35,74,20,4.00,few clouds
12,12,Takoradi,GH,4.8845,-1.7554,81.03,82,25,9.13,scattered clouds
13,13,Chabahar,IR,25.2919,60.6430,70.47,57,100,4.45,overcast clouds
17,17,Hobart,AU,-42.8794,147.3294,68.02,57,40,1.99,scattered clouds
19,19,Manoel Urbano,BR,-8.8389,-69.2597,79.18,96,98,1.95,overcast clouds
20,20,Poum,NC,-20.2333,164.0167,77.97,70,8,7.20,clear sky
24,24,Punta Arenas,CL,-53.1500,-70.9167,69.91,40,0,25.32,clear sky
25,25,Ponta Do Sol,PT,32.6667,-17.1000,66.83,77,53,12.66,broken clouds
26,26,Cape Town,ZA,-33.9258,18.4232,69.12,73,0,1.01,clear sky
27,27,Butaritari,KI,3.0707,172.7902,82.00,80,83,17.40,light rain
30,30,Sibolga,ID,1.7427,98.7792,73.76,97,100,3.33,overcast clouds
31,31,Rikitea,PF,-23.1203,-134.9692,77.54,76,85,7.38,light rain
33,33,Mount Isa,AU,-20.7333,139.5000,80.37,69,1,0.00,clear sky
36,36,Port Alfred,ZA,-33.5906,26.8910,65.19,76,14,23.85,few clouds
37,37,Ushuaia,AR,-54.8000,-68.3000,64.06,45,20,17.27,few clouds

In [33]:
# 4a. Determine if there are any empty rows.
preferred_cities_df.isnull().sum()

City_ID                0
City                   0
Country                0
Lat                    0
Lng                    0
Max Temp               0
Humidity               0
Cloudiness             0
Wind Speed             0
Current Description    0
dtype: int64

In [34]:
# 4b. Drop any empty rows and create a new DataFrame that doesn’t have empty rows.
clean_df = preferred_cities_df.dropna()
clean_df

,City_ID,City,Country,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed,Current Description
1,1,Atuona,PF,-9.8000,-139.0333,78.22,73,20,11.43,few clouds
3,3,Carnarvon,AU,-24.8667,113.6333,68.07,73,0,13.80,clear sky
6,6,Arraial Do Cabo,BR,-22.9661,-42.0278,75.16,78,75,8.05,broken clouds
7,7,Kavieng,PG,-2.5744,150.7967,81.37,78,99,7.38,light rain
8,8,Aketi,CD,2.7388,23.7833,73.80,73,80,2.35,broken clouds
10,10,Oranjestad,AW,12.5240,-70.0270,82.35,74,20,4.00,few clouds
12,12,Takoradi,GH,4.8845,-1.7554,81.03,82,25,9.13,scattered clouds
13,13,Chabahar,IR,25.2919,60.6430,70.47,57,100,4.45,overcast clouds
17,17,Hobart,AU,-42.8794,147.3294,68.02,57,40,1.99,scattered clouds
19,19,Manoel Urbano,BR,-8.8389,-69.2597,79.18,96,98,1.95,overcast clouds
20,20,Poum,NC,-20.2333,164.0167,77.97,70,8,7.20,clear sky
24,24,Punta Arenas,CL,-53.1500,-70.9167,69.91,40,0,25.32,clear sky
25,25,Ponta Do Sol,PT,32.6667,-17.1000,66.83,77,53,12.66,broken clouds
26,26,Cape Town,ZA,-33.9258,18.4232,69.12,73,0,1.01,clear sky
27,27,Butaritari,KI,3.0707,172.7902,82.00,80,83,17.40,light rain
30,30,Sibolga,ID,1.7427,98.7792,73.76,97,100,3.33,overcast clouds
31,31,Rikitea,PF,-23.1203,-134.9692,77.54,76,85,7.38,light rain
33,33,Mount Isa,AU,-20.7333,139.5000,80.37,69,1,0.00,clear sky
36,36,Port Alfred,ZA,-33.5906,26.8910,65.19,76,14,23.85,few clouds
37,37,Ushuaia,AR,-54.8000,-68.3000,64.06,45,20,17.27,few clouds

In [35]:
# 5a. Create DataFrame called hotel_df to store hotel names along with city, country, max temp, and coordinates.
hotel_df = clean_df[["City", "Country", "Max Temp", "Current Description", "Lat", "Lng"]].copy()

# 5b. Create a new column "Hotel Name"
hotel_df["Hotel Name"] = " "
hotel_df.head(10)

,City,Country,Max Temp,Current Description,Lat,Lng,Hotel Name
1,Atuona,PF,78.22,few clouds,-9.8000,-139.0333,
3,Carnarvon,AU,68.07,clear sky,-24.8667,113.6333,
6,Arraial Do Cabo,BR,75.16,broken clouds,-22.9661,-42.0278,
7,Kavieng,PG,81.37,light rain,-2.5744,150.7967,
8,Aketi,CD,73.80,broken clouds,2.7388,23.7833,
10,Oranjestad,AW,82.35,few clouds,12.5240,-70.0270,
12,Takoradi,GH,81.03,scattered clouds,4.8845,-1.7554,
13,Chabahar,IR,70.47,overcast clouds,25.2919,60.6430,
17,Hobart,AU,68.02,scattered clouds,-42.8794,147.3294,
19,Manoel Urbano,BR,79.18,overcast clouds,-8.8389,-69.2597,

In [36]:
# 6a. Set parameters to search for hotels with 5000 meters.
params = {
    "radius": 5000,
    "type": "lodging",
    "key": g_key
}

# 6b. Iterate through the hotel DataFrame.
for index, row in hotel_df.iterrows():
    
    # 6c. Get latitude and longitude from DataFrame
    lat = row["Lat"]
    lng = row["Lng"]
    params["location"] = f"{lat},{lng}"
    
    # 6d. Set up the base URL for the Google Directions API to get JSON data.
    base_url = "https://maps.googleapis.com/maps/api/place/nearbysearch/json"

    # 6e. Make request and retrieve the JSON data from the search. 
    hotels = requests.get(base_url, params=params).json()
   
    
    # 6f. Get the first hotel from the results and store the name, if a hotel isn't found skip the city.
    try:
        hotel_df.loc[index, "Hotel Name"] = hotels["results"][0]["name"]
        
    except (IndexError):
        print("Cannot find hotel...skipping.")

Cannot find hotel...skipping.

In [37]:
# 7. Drop the rows where there is no Hotel Name.
c = hotel_df.replace(r'^\s*$', np.nan, regex=True)
clean_hotel_df = c.dropna()
clean_hotel_df

,City,Country,Max Temp,Current Description,Lat,Lng,Hotel Name
1,Atuona,PF,78.22,few clouds,-9.8000,-139.0333,Villa Enata
3,Carnarvon,AU,68.07,clear sky,-24.8667,113.6333,Hospitality Carnarvon
6,Arraial Do Cabo,BR,75.16,broken clouds,-22.9661,-42.0278,Pousada Porto Praia
7,Kavieng,PG,81.37,light rain,-2.5744,150.7967,Nusa Island Retreat
10,Oranjestad,AW,82.35,few clouds,12.5240,-70.0270,Divi Village Golf & Beach Resort
12,Takoradi,GH,81.03,scattered clouds,4.8845,-1.7554,Raybow International Hotel
13,Chabahar,IR,70.47,overcast clouds,25.2919,60.6430,هتل گدروشیا
17,Hobart,AU,68.02,scattered clouds,-42.8794,147.3294,Mantra on Collins Hobart
19,Manoel Urbano,BR,79.18,overcast clouds,-8.8389,-69.2597,Baixada Beira Rio
20,Poum,NC,77.97,clear sky,-20.2333,164.0167,Gîte kajeon
24,Punta Arenas,CL,69.91,clear sky,-53.1500,-70.9167,Hotel Hain
25,Ponta Do Sol,PT,66.83,broken clouds,32.6667,-17.1000,Hotel do Campo
26,Cape Town,ZA,69.12,clear sky,-33.9258,18.4232,Southern Sun Waterfront Cape Town
27,Butaritari,KI,82.00,light rain,3.0707,172.7902,Isles Sunset Lodge
30,Sibolga,ID,73.76,overcast clouds,1.7427,98.7792,Hotel Syariah CN Darussalam
31,Rikitea,PF,77.54,light rain,-23.1203,-134.9692,People ThankYou
33,Mount Isa,AU,80.37,clear sky,-20.7333,139.5000,ibis Styles Mt Isa Verona
36,Port Alfred,ZA,65.19,few clouds,-33.5906,26.8910,The Halyards Hotel
37,Ushuaia,AR,64.06,few clouds,-54.8000,-68.3000,Albatros Hotel

In [38]:
# 8a. Create the output File (CSV)
output_data_file = "weatherpy_vacation.csv"
# 8b. Export the City_Data into a csv
clean_hotel_df.to_csv(output_data_file, index_label="City_ID")

In [39]:
# 9. Using the template add city name, the country code, the weather description and maximum temperature for the city.
info_box_template = """
<dl>
<dt>Hotel Name</dt><dd>{Hotel Name}</dd>
<dt>City</dt><dd>{City}</dd>
<dt>Country</dt><dd>{Country}</dd>
<dt>Weather Description</dt><dd>{Current Description}</dd>
<dt>Max Temp</dt><dd>{Max Temp} °F</dd>
</dl>
"""

# 10a. Get the data from each row and add it to the formatting template and store the data in a list.
hotel_info = [info_box_template.format(**row) for index, row in clean_hotel_df.iterrows()]

# 10b. Get the latitude and longitude from each row and store in a new DataFrame.
locations = clean_hotel_df[["Lat", "Lng"]]

In [40]:
# 11a. Add a marker layer for each city to the map. 
locations = clean_hotel_df[["Lat", "Lng"]]
max_temp = clean_hotel_df["Max Temp"]
fig = gmaps.figure(center=(30.0, 31.0), zoom_level=1.5)
heat_layer = gmaps.heatmap_layer(locations, weights=max_temp,dissipating=False,
             max_intensity=300, point_radius=4)
marker_layer = gmaps.marker_layer(locations, info_box_content=hotel_info)
fig.add_layer(heat_layer)
fig.add_layer(marker_layer)
# 11b. Display the figure 
fig

Figure(layout=FigureLayout(height='420px'))